### ISSUE TITLE
Quarries regarding r3PG model 

### ISSUE THREAD

**Issue by ChaitraliGore** [trotsiuk/r3PG#100]
Hello developers, 

1) My name is Chaitrali. In my dissertation work, which centers on the utilization of the r3PG model, I've employed default parameter values sourced from literature pertaining to Teak species. For the sensitivity analysis, I've introduced ranges of ±20%, ±30%, and ±60% for the minimum and maximum values of parameters. However, I've observed that each range yields a different number of sensitive parameter values. How can I determine the accuracy of each range?

2) I'm interested in understanding how the error values for output variables such as height, DBH, and biomass for stem, root, and foliage are calculated within the r3PG model. Specifically, when utilizing default parameter values, the likelihood value I obtained was -688188. Could you elucidate the methodology behind calculating these error values?

3) Concerning the MCMC procedure within the r3PG model, is it obligatory to execute it for 60 lakh iterations with a chain count of 3, or is there flexibility to modify these parameters based on specific requirements?

4) Given that I'm focusing on a single species across various sites in my study, what steps should I take to run the r3PG model for multiple sites within a single execution?

5) Regarding the default value of 1 provided in the thinning aspect of the r3PG model, could you provide clarification on its interpretation and significance within the context of the model's functionality?

Have a nice day....!!!

**Comment by trotsiuk** [comment]
Hello @ChaitraliGore 

1. It is advisable to narrow the uncertainty range of the parameters as much as possible. If you are very unsure about the parameters ranges, then the wider range would be more applicable. The variation in the number of sensitive parameter values across different ranges (±20%, ±30%, and ±60%) is expected, as sensitivity analysis explores how changes in model input (parameters in this case) influence model output. To determine the accuracy of each range, consider the model's response curve to parameter variations. Typically, a more sensitive parameter will have a larger impact on model output even with small changes. 

2. In the context of the r3PG model, error values for output variables (height, DBH, biomass, etc.) are often calculated using observed data versus model-predicted values. Common methods include Root Mean Square Error (RMSE) or Mean Absolute Error (MAE), among others. In the [vignette example](https://htmlpreview.github.io/?https://github.com/trotsiuk/r3PG/blob/master/vignettes/r3PG-ReferenceManual.html) is is done `r3pg_ll`. Understanding the statistical framework used (e.g., Bayesian inference, likelihood-based approaches) and how the model's predictions deviate from observed data would be useful in this case.

3. The Markov Chain Monte Carlo (MCMC) procedure is a robust statistical method for estimating the distribution of model parameters. While 60 iterations with a chain count of 3 is a substantial sampling effort, the necessity and sufficiency depend on the convergence criteria of your model parameters. It's advisable to use diagnostic tools (e.g., Gelman-Rubin statistic) to assess convergence; you may adjust the iteration count and chain numbers based on these assessments to ensure adequate parameter space exploration while maintaining computational efficiency.

4. You can use the same approach as described in the [vignette example](https://htmlpreview.github.io/?https://github.com/trotsiuk/r3PG/blob/master/vignettes/r3PG-ReferenceManual.html)  for multiple sites.

5. The value 1 indicate that there is no differentiation between thinning from above or below. For more information please refer to the original [3-PG manual](https://3pg.sites.olt.ubc.ca/files/2014/04/3PGpjs_UserManual.pdf) (`Fractions greater than 1 simulate thinning from above.`).

I hope this response is helpful.

**Comment by ChaitraliGore** [comment]
Thank You.....!!! The above guidance is very helpful. 
 
 after running Bayesian calibration with a massive 400,000 iteration cycle and 3 chains, you're facing an issue where the final graph isn't displaying the default and calibrated data as expected. The 5% and 95% interval values are showing up as null, and for variables like biomass, dbh, and height, only the first default value is being shown for the calibrated values.
What steps can I take to address this issue?

![Calibrated_Map](https://github.com/trotsiuk/r3PG/assets/161599945/aa40b6b6-f244-4f6d-b2b2-6e4a5e530235)
 for the reference I am sharing the calibration map.
