### ISSUE TITLE
Order in morris plot in Vignette

### ISSUE THREAD

**Issue by LisaHuelsmann** [trotsiuk/r3PG#101]
Hi @trotsiuk, 
I'm using your package for teaching again this week and I noticed that the results of the morris sensitivity analysis have not exactly the right order. I think the idea would be to order the parameters according to mu.star but in the figure it seems to be a mix of mu.star and sigma. In case you want to change this, here is how I implemented it:

```
morrisOut.df <- data.frame(
  parameter = par_cal_names,
  mu.star = apply(abs(morrisOut$ee), 2, mean, na.rm = T),
  sigma = apply(morrisOut$ee, 2, sd, na.rm = T)
) %>%
  arrange( mu.star ) %>% 
  mutate(parameter = reorder(parameter, mu.star))

morrisOut.df %>%
  gather(variable, value, -parameter) %>%
  ggplot(aes(parameter, value, fill = variable), color = NA)+
  geom_bar(position = position_dodge(), stat = 'identity') +
  scale_fill_brewer("", labels = c('mu.star' = expression(mu * "*"), 'sigma' = expression(sigma)), palette="Dark2") +
  theme_classic() +
  theme(
    axis.text = element_text(size = 6),
    axis.text.x = element_text(angle=90, hjust=1, vjust = 0.5),
    axis.title = element_blank(),
    legend.position = c(0.05 ,0.95),legend.justification = c(0.05,0.95)
  )
```

Interestingly I also get Inf for mu.star of err_biom_foliage. Not sure if this indicates a problem?

Hope you're doing well.

**Comment by trotsiuk** [comment]
Hi @LisaHuelsmann 

Thanks for the hint and happy to hear that the package is still in use :). I have now added `mutate(parameter = reorder(parameter, mu.star))` to the vignette to forth the re-ordering. 

Yes, the `err_biom_foliage` was creating one `Inf` value during the sensitivity analysis. This has resulted in the `Inf` in the summary and wrong visualization. I have now corrected it with `mourrisOut.ee <- na.omit(morrisOut$ee)`. Thanks for it!
