### ISSUE TITLE
Height equation

### ISSUE THREAD

**Issue by trotsiuk** [trotsiuk/r3PG#13]
Add the option for multiple height equations:

A Michajlow (or Schumacher) function (Michajlow, 1952) is used to predict heights and live crown lengths. The version without the “ +n_HC×C×DBH “ was found to be the most appropriate for the EFM data by Zell (2016).

y=1.3+a_H×e^((-n_HB)⁄DBH)+n_HC×C×DBH						

where y is height (HTOT ) or live-crown length (LCL) in metres, C is the competition variable of 3-PG, aH, nHB and nHC are fitted parameters for 3-PG and DBH is diameter at 1.3 m in cm.

References

Michajlow, J., 1952. Mathematische Formulierung des Gesetzes für Wachstum und Zuwachs der Waldbäume und Bestände. Schweiz. Z. Forstw 103, 368-380.
Zell, J., 2016. A climate sensitive single tree stand simulator for Switzerland. Birmensdorf, Swiss Federal Institute of Forest, Snow and Landscape Research WSL. 107 p.

[nonlinearfunction.docx](https://github.com/trotsiuk/r3PG/files/4449483/nonlinearfunction.docx)

**Comment by trotsiuk** [comment]
@DavidForrester currently to calculate LCL we are also using LAI and relative height. According to your request we shall not use it any longer and use only competition?

Vova

**Comment by DavidForrester** [comment]
Yes, for the option of the non-linear model, the LAI and relative height parameters are not applicable and should be 0. For the linear model, all parameters can still be used.

Critically, I forgot to mention that the bias corrections should not be applied for the non-linear height or LCL models. Sorry.

**Comment by trotsiuk** [comment]
Tnanks @DavidForrester and what about `crown_width` - shall the calculation be changed as Height or LCL or keep linear model?

**Comment by DavidForrester** [comment]
The crown_width calculation stays only as a linear equation. The crown equation does not break down for large tree sizes like the height and LCL equations.
