### ISSUE TITLE
Pruning and irrigation in the management options

### ISSUE THREAD

**Issue by DavidForrester** [trotsiuk/r3PG#15]
It would be useful to add the pruning and irrigation options to the management available in r3PG, in the same way as currently in VBA.

**Comment by trotsiuk** [comment]
@DavidForrester Would be great if you can provide me with the 
- required input for pruning and irrigation
- VBA output example

**Comment by trotsiuk** [comment]
from @DavidForrester 

```
 These are applied in the same way as the Vary Block, which is
used to change parameter values during a rotation. This is explained more
in the manual. This varying of parameters is sometimes used to simulate
changes that occur within the stand that are not otherwise accounted for by
3-PG. Perhaps in r3PG you will be able to implement the silvicultural
events and the vary blocks in the same way.

The fertiliser and irrigation examples are in the worksheets:
-	SE Qld (a)
-	SE Qld (b)
The vary block inputs (not used in the attached simulations) are shown in
the worksheet Varyblocks.
```


[ExampleMixtureRuns_prune_irrigation.xls.zip](https://github.com/trotsiuk/r3PG/files/4473903/ExampleMixtureRuns_prune_irrigation.xls.zip)

**Comment by trotsiuk** [comment]
@DavidForrester 
From my perspectives the easiest way to implement it would be the following:

- **Fertility and Irrigation**
I would suggest to add two more optional columns to the climate data: `fr` and `irrigation`. In this way user can specify monthly specific values. I think this might be interesting and important especially for irrigation. From the negative site, is that the user would have to re-calculate it on which year it occurs (not age). Furthermore, if one provide only average climate (e.g. 12 month) It will be not really possible to specify age/time depended fertility, only if you expand this climate to longer period (can be done with `prepare_climate()` function. But from positive side I will not have to add two new tables as input.

- **Defoliation**
I guess it shall be applied to similar way as thinning. 

- **Varyblock**
It is an interesting option to interact with model. Potentially I can see the option, where user provide additional table, that spans `from` - `to` period (identical in number of rows as climate table), where one can enter optional columns with parameter names and provide their values for the whole period of simulation.  Potentially one can also have `fr` and `irrigation` here. This however starts to be a bit more complex if we have multiple species.

**Comment by DavidForrester** [comment]
Your suggestions sound good to me, but the fertility and irrigation could be done the same way as a vary block and then would not need to be combined with climate information. This would also prevent the user from needing to interpolate information.

The values provided in the vary blocks and silvicultural information i VBA can change at the date specified or be interplotated to gradually change. This is the description in the manual:
Interpolate lookups (Yes/No) determines how silvicultural event tables relating to Fertiliser, Irrigation and minimum ASW (minASW), are treated. This also applies to the Vary Blocks. If interpolate lookups = No then the values will be used for the age entered and not changed until the next age that was provided. If interpolate lookups = Yes then linear interpolation will be used to estimate the values for ages where values were not provided.

**Comment by trotsiuk** [comment]
Thanks @DavidForrester 

While `irrigation` and `fertility` is relatively easy to implement, I'm currently struggling to find a good solution for implementing the vary block for other `parameters`. From your opinion, how important and widely used is this option? If this is not something people often use, I would rather tend to avoid implementing it as this stage.

**Comment by DavidForrester** [comment]
It is probably okay to implement it later. The studies that use it are usually those that are looking in detail at the physiology and reasons behind the responses, as opposed to those focusing on growth responses.

**Comment by florianhartig** [comment]
Hi guys, I'm just looking over the open issues, and move this to future development, as I thought it would be good to have it, but maybe not before we submit the package to CRAN (which we could do this week I think).
