### ISSUE TITLE
Should f_3PG be exported?

### ISSUE THREAD

**Issue by florianhartig** [trotsiuk/r3PG#16]
What it said - ist it necessary to export this function, or should we hide it from the user? In the latter case, set @keywords internal

**Comment by florianhartig** [comment]
Just do add on this - it wasn't quite clear to me if there is any reason to have 2 functions that do the same thing.

**Comment by trotsiuk** [comment]
My idea behind is that:
`run_3pg` - do all the checks, make replacement, make the transformations, etc
`f_3PG` - assumes that all input data are in correct shape and format. E.g. for MCMC I would use f_3PG as it is a bit faster, but if one run it for Millions of iteration you can gain quite a bit

**Comment by florianhartig** [comment]
hmm ... OK, might make sense - I'll document this a bit stronger in the help then!

**Comment by florianhartig** [comment]
just a side note: if you optimize for speed, then why still do df_out?

**Comment by trotsiuk** [comment]
Yeh, that is true. I thought to have the output option be consistent with `run_3PG`. But I agree that  it will not be used. 
Agree to remove `df_out`.

**Comment by trotsiuk** [comment]
Probably also some arguments (n_sp,  n_m,  n_man, t_t,) shall be calculated inside. It is only number of rows, and columns. Also there is no need for sp_names input.

I can adjust the `f_3PG` function if you want

**Comment by trotsiuk** [comment]
Ok @florianhartig I think you are right. Probably the best would be to keep only one function `run_3PG`. Within `run_3PG` there will be an option `check_input = TRUE` to check the input. If `check_input = FALSE` then we will skip all the checks and test and only run the fortran assuming that input is correct. 
Additionally there will be `prepare_climate` and `prepare_inputs` functions which will do the check and structuring. They would be exportable.

This all will require quite some modification. I can do all of this and later you can do more comments and suggestions.

Let me know

**Comment by florianhartig** [comment]
Yes, I think that's better. Easier for the user, easier to maintain for us, and will only cost 2 if statements, this is minimal.
