### ISSUE TITLE
Output format of run_3PG if df_out = TRUE

### ISSUE THREAD

**Issue by florianhartig** [trotsiuk/r3PG#17]
The help says if the function returns a 4-dimensional array, but it is actually a list of lists. Ist this intended / was this changed later?

**Comment by trotsiuk** [comment]
Ah, yes. Sorry. It was changed later to be consistent with `run_3PG`

**Comment by florianhartig** [comment]
So, what should we write about the output format then, just that it's a list of lists?

**Comment by trotsiuk** [comment]
Since we will remove the `f_3PG` function I think the 'tranf_out' function will be only internal. And the output of the `run_3PG` will be either `long format data frame` or `4-d array`.
