### ISSUE TITLE
change naming for sub_climate?

### ISSUE THREAD

**Issue by florianhartig** [trotsiuk/r3PG#18]
Hi Vova, it's more a question of style, but recommendation is that function names should be understandable. If I understand correctly, sub_climate can be used to subset or replicate climate data. Maybe "prepareClimateTable" would be a more accurate / understandable name?

**Comment by trotsiuk** [comment]
sounds good!

**Comment by florianhartig** [comment]
OK, I will change that!

**Comment by florianhartig** [comment]
Actually, according to your naming convention, it should probably be prepare_climate_table

**Comment by trotsiuk** [comment]
I think will be enough to `prepare_climate`

**Comment by florianhartig** [comment]
ok, will do that
