### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by florianhartig** [trotsiuk/r3PG#19]
We should add some testthat unit tests. I would suggest that we make 3 test cases for the run function

* test the basic functionality
* tests for sanity (could be done together with the latter), i.e. that changes in recommended parameter space don't create crazy results
* tests for compatibility with the other model versions, i.e. that results are similar than the virtual basic versions.

For the later, I thought we could run the virtual basic model with the vignette drivers for a few parameter combinations (for both model versions), and then check in the test that the new version delivers close to identical results? This way, we can also immediately check this off the list of things to do for the paper/

**Comment by trotsiuk** [comment]
I Don't really understand this @florianhartig 

- For the first point, that is understandable.

- For the second and third, I don't really understand. The comparison with VBA is in the [`data-raw`](https://github.com/trotsiuk/r3PG/tree/master/pkg/data-raw/r_vba_compare) subfolder, where we do compare with @DavidForrester multiple versions of the output. The outputs are identical up to 6-7 decimal points.

**Comment by florianhartig** [comment]
Hi Vova, ah, I didn't know this - that's excellent, so why not make this a unit test, so that it's run every time we make an update to the model? I think this would be an excellent check of the code.

**Comment by trotsiuk** [comment]
This is possible. Maybe not with all examples those, as then we would need to add another site to the internal data. with VBA we compare multiple sites, but for the r3PG I save only one site as internal data.

**Comment by trotsiuk** [comment]
Hi @florianhartig I have added the unit test to check if the output of the model (biomass stem, foliage, and root) is as expected in the end of simulations for 5 distinct model runs: 3-PGpjs, 3PGmix and mixtures

**Comment by florianhartig** [comment]
looks good to me, thanks!
