### ISSUE TITLE
soil classes

### ISSUE THREAD

**Issue by DavidForrester** [trotsiuk/r3PG#21]
I also saw that the soil textures are defined in the d_site, which is good (I still don’t know why they are considered species parameters in VBA). But in the VBA version, when the soil classes are defined in this way, there are only about 4 classes. But in reality, there is a gradient of soil types and that is when the “species parameters” SWconst and SWpower were useful – this was commonly used. I think this can be solved by adding more options to the 4 that you already have, as shown in the attached excel file. Another option would be to have the soil class in the d_site specified using both SWconst and SWpower.
[soil_textures.xlsx](https://github.com/trotsiuk/r3PG/files/4488583/soil_textures.xlsx)

**Comment by trotsiuk** [comment]
HI David. 

I think the `r3PG` do it in similar way as `VBA`. 

```
        if ( soil_class > 0.d0 ) then
            ! Standard soil type
            SWconst(:) = 0.8d0 - 0.10d0 * soil_class
            SWpower(:) = 11.d0 - 2.d0 * soil_class
        elseIf ( soil_class < 0.d0 ) then
            ! Use supplied parameters
            SWconst(:) = SWconst0(:)
            SWpower(:) = SWpower0(:)
        else
            ! No soil-water effects
            SWconst(:) = 999
            SWpower(:) = SWpower0(:)
        end if
```

Meaning that if soil class provided (any real number > 0) the `SWconst, -power` are calculated, if soil class is equal to 0, then user can provide his `SWconst, -power`  in the `parameters` table.

**Comment by DavidForrester** [comment]
That sounds good.
