### ISSUE TITLE
3-PG manual

### ISSUE THREAD

**Issue by DavidForrester** [trotsiuk/r3PG#22]
Would it be possible to somewhere refer to the manual I wrote? It points people in the direction of different sources of information and hopefully facilitates higher quality use of 3-PG. It is not a replacement for the Sands work, but it tries to fill in some information that appears to be misunderstood when trying to obtain data to estimate the parameters. 

Forrester, D. I., 2020. 3-PG User Manual (available from https://sites.google.com/site/davidforresterssite/home/projects/3PGmix/3pgmixdownload). Swiss Federal Institute for Forest, Snow and Landscape Research WSL, Birmensdorf, Switzerland. 70 p.

**Comment by trotsiuk** [comment]
@DavidForrester I would refer it in the package description. 

Would you accept if I put all the files in the zip file into `r3PG` package? I will create the subdirectory in the package which will be accessible to everyone. In this way All the information will stay at one place?

**Comment by florianhartig** [comment]
Hi Vova / David - I'm not sure if it's a good idea to have it in the package, because this would move the files to the R install directories, and I doubt people would find them there. Better add a link to Davids page (where people can download the zip file), or else we could also store a copy of the zip file on our GitHub page (but outside the package)

**Comment by trotsiuk** [comment]
ok, then we can just add reference in the package description and on GitHub main page of the package

**Comment by trotsiuk** [comment]
Idea was not really to put it to the `inst` directory, but to e.g. `data-raw`, which are hidden from build. This mainly to keep it on Github, so everything is in one place

**Comment by DavidForrester** [comment]
I will add a citation within the R documentation. This way I can continue to update it on my website, so that there is only one source.
