### ISSUE TITLE
Preparing CRAN submission 0.1.0

### ISSUE THREAD

**Issue by florianhartig** [trotsiuk/r3PG#23]
Issue to collect last points / discuss for the first CRAN submission.

Vova, have you run the package through winbuilder already? I can't do it, because emails always go to the maintainer.

**Comment by trotsiuk** [comment]
- [x] - yes, I have run it trough winbuilder. Usually do it always once pushed. There was small notes at the beginning (like title shall start with capital, ..), but now seems file. I will check it again once the changes done. I also did some other smaller tests like devtools::spell_check(), ..

**Comment by florianhartig** [comment]
Hi Vova, I have suggested a few smaller things in https://github.com/trotsiuk/r3PG/pulls, but I think the package is overall fine. I only think it would be good to solve https://github.com/trotsiuk/r3PG/issues/27 so that the users are not frustrated by not getting the data.

**Comment by trotsiuk** [comment]
CRAN comments 1

- [ ] Please use the description field to explain and elaborate on specific terms terms used in the title and description field.
- [ ] Please always explain all acronyms in the description text.

- [ ] If there are references describing the methods in your package, please add these in the description field of your DESCRIPTION file in the form
authors (year) <doi:...>
authors (year) <arXiv:...>
authors (year, ISBN:...)
or if those are not available: <https:...>
with no space after 'doi:', 'arXiv:', 'https:' and angle brackets for auto-linking.
(If you want to add a title as well please put it in quotes: "Title")

- [ ] Please add \value to .Rd files regarding exported methods and explain the functions results in the documentation. Please write about the structure of the output (class) and also what the output means.
(If a function does not return a value, please document that too, e.g. \value{No return value, called for side effects} or similar)

**Comment by trotsiuk** [comment]
HI @florianhartig, I have adjusted the 3 and 4 request from CRAN, but not sure about first two. Would you have suggestions?

For the request 1 Not sure to what exactly they are referring. We use a lot 3-PG model, shall it be expanded? See the next point.

For the request 2 I think they are referring to `3-PGpjs` and `3-PGmix` in `run_3PG` function. I'm not sure if we need to expand each of them to e.g. Physiological Processes Predicting Growth 3-PG model. Or I shall write in the response that those are acronyms of the model? I don't know if they are referring to any other acronyms?

**Comment by florianhartig** [comment]
Hi Vova, very sorry, I just read this now that I'm looking over the paper, but it seems you sorted this out?

**Comment by trotsiuk** [comment]
On CRAN now https://cran.r-project.org/web/packages/r3PG/index.html

**Comment by trotsiuk** [comment]
Hi @florianhartig I got e-mail from CRAN

```
Dear maintainer,
Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_r3PG.html>.
Please correct before 2020-05-26 to safely retain your package on CRAN.
The CRAN Team

src/Makevars has

all: $(SHLIB) clean

'Writing R Extensions' warned you that was wrong, and it leads to frequent failures with parallel makes.
```

I think this is one of their new checks (similar found here for [rstantools](https://github.com/stan-dev/rstantools/issues/71))

Do you have a suggestion?

**Comment by trotsiuk** [comment]
Ok, I think I have fixed it based on this [Fix for parallel make based on Brian Ripley](https://github.com/aadler/SimpFort/commit/e9aa218bdb25aadcdeafeb1a410a82b7c48a3c2c) and [this](https://www.avrahamadler.com/2018/12/09/the-need-for-speed-part-1-building-an-r-package-with-fortran/)

I will run the tests again. 

Do you think I shall 'resubmit' the package and change the version or, resubmit and keep the version, or how does it work? I have no experience

**Comment by florianhartig** [comment]
Definitely a new version - let's close this here, 0.1.0 is on CRAN now, so this is done! Release is in https://github.com/trotsiuk/r3PG/releases/tag/v0.1.0
