### ISSUE TITLE
CRAN and NEWS file

### ISSUE THREAD

**Issue by florianhartig** [trotsiuk/r3PG#24]
Hi Vova,

in https://github.com/trotsiuk/r3PG/commit/c226caddedb0927942563ca72d599b3ead0eafa5 I created a CRAN and NEWS file.

The NEWS file is required (or at least strongly recommended), to document the changes in each release. I usually copy what's written there also to the CRAN submission and to GitHub releases https://github.com/trotsiuk/r3PG/releases which I would do at least for every CRAN release, I often do intermediate releases as well. 

THe CRAN file is for our own documentation, but most packages do this - paste there the text you write in your CRAN submission, plus the responses you get. 

At the moment, I just copied over the text from DHARMa and modified to have a bare minimum. Feel free to modify / populate this.

**Comment by trotsiuk** [comment]
This sounds great!

**Comment by trotsiuk** [comment]
Florian, [Travis](https://travis-ci.org/github/trotsiuk/r3PG/jobs/677200090) is alarming error now after adding the CRAN and NEWS file. Do you know the issue, I can't find out why. It error on installing many packages, such as `Rglpk`.

**Comment by florianhartig** [comment]
No idea what happened - I reverted the commit, but still produces an error. Maybe a coincidental change in TRAVIS?

**Comment by florianhartig** [comment]
I pushed my changes into https://github.com/trotsiuk/r3PG/tree/CRAN-preparation now, and the master should be identical to what it was before, no idea why it still fails.

**Comment by trotsiuk** [comment]
Yes, it somehow weird. I also tried. Travis CI try to install packages which are not related to r3PG in any sense

```
Installing 8 packages: spaMM, ROI, ROI.plugin.glpk, registry, slam, Rglpk, tibble, tinytex
```

**Comment by florianhartig** [comment]
Note - I have added the files again, but they are now in https://github.com/trotsiuk/r3PG/tree/CRAN-preparation ... I will push my changes there and then create a pull request for you to check

**Comment by florianhartig** [comment]
This is in https://github.com/trotsiuk/r3PG/pulls
