### ISSUE TITLE
Change pkg to r3PG?

### ISSUE THREAD

**Issue by florianhartig** [trotsiuk/r3PG#25]
This is just cosmetic, but I wonder if it would look nicer to change the pck subfolder to r3PG? At least it seems to me that most packages I know (at least mine) have this structure. Maybe I'm just projecting my preference on this, however, technically, it doesn't really matter

**Comment by trotsiuk** [comment]
Yes, I think we can do it. I actually switched it back and forth twice already I think. For me was just a bit confusing if we have r3PG the main folder and then again r3PG subfolder, I was lost sometimes in which I'm :)

**Comment by florianhartig** [comment]
As I said, it's more a personal preference, I prefer the package name, but if you prefer pck then there's no reason not to keep it like it is.

**Comment by florianhartig** [comment]
I pushed my changes into a new branch https://github.com/trotsiuk/r3PG/tree/CRAN-preparation - will work there for now.

The master should be identical to what it was before, but I have no idea why the travis commit still fails.

**Comment by trotsiuk** [comment]
After thinking a while, I have decided to keep it as `pkg`, this will brings a bit diversity to yours package structure :)
