### ISSUE TITLE
Travis CI build error

### ISSUE THREAD

**Issue by florianhartig** [trotsiuk/r3PG#26]
OK, I'll file an issue now because a colleague told me they have exactly the same problem with BayesianTools, so maybe worth discussing it here. 

During install, we are getting the following error on Travis for builds that definitely ran through on Travis before

```
* DONE (ROI)
* installing *source* package ‘Rglpk’ ...
** package ‘Rglpk’ successfully unpacked and MD5 sums checked
** libs
/bin/bash: line 0: cd: GLPK: No such file or directory
Makevars:10: recipe for target 'GLPK.ts' failed
make: *** [GLPK.ts] Error 1
ERROR: compilation failed for package ‘Rglpk’
* removing ‘/home/travis/R/Library/Rglpk’
Error in i.p(...) : 
  (converted from warning) installation of package ‘Rglpk’ had non-zero exit status
Calls: <Anonymous> ... with_rprofile_user -> with_envvar -> force -> force -> i.p
Execution halted
The command "Rscript -e 'deps <- remotes::dev_package_deps(dependencies = NA);remotes::install_deps(dependencies = TRUE);if (!all(deps$package %in% installed.packages())) { message("missing: ", paste(setdiff(deps$package, installed.packages()), collapse=", ")); q(status = 1, save = "no")}'" failed and exited with 1 during .
Your build has been stopped.
```

It's unclear if something is going wrong on Travis, whether a package dependency has somehow changed and breaks the build, or something else. I don't have any problems locally, but I haven't re-installed all my packages.

**Comment by trotsiuk** [comment]
in a way it is good to hear that we are not alone.

**Comment by florianhartig** [comment]
OK, the problem is here https://github.com/florianhartig/DHARMa/issues/166

What I would suggest is that we remove BT from suggest until this problem is solved.

**Comment by florianhartig** [comment]
OK, apart from that, I think I found the problem in the Travis builds. I fixed this in https://github.com/trotsiuk/r3PG/tree/CRAN-preparation and added BayesianTools again. If this works, we can merge it back to master with my other changes
