### ISSUE TITLE
Load data in vignette

### ISSUE THREAD

**Issue by florianhartig** [trotsiuk/r3PG#27]
In the vignette, if we do

`load('vignette_data/solling.rda')` 

this works for us, but not for the user, right? We could probably directly load from the internet, as in 

`https://raw.githubusercontent.com/trotsiuk/r3PG/master/pkg/data-raw/vignette_data/solling.rda`

If we do this, we could also move the data out of the package, e.g. in the repo under a folder data. It would even be possible to provide further datasets there.

**Comment by trotsiuk** [comment]
Yes, this is a good idea. Maybe we can create a new repository, something like `r3PG-utils` where we will move the data and vignette preparation, more extensive comparison with VBA, ets. And then then we add the link to vignette data?

**Comment by trotsiuk** [comment]
Or maybe it is simply enough to put it not in `pkg` subdirectory, but in the main directory. I don't know what is better, to separate it into separate repository, or to keep together (probably easier to track).
