### ISSUE TITLE
Link to other packages?

### ISSUE THREAD

**Issue by florianhartig** [trotsiuk/r3PG#31]
Just posting this here so that I don't forget it - should we link somewhere to other R packages that implement 3PG? e.g. https://github.com/griffithdan/r3PG and the one from Francesco?

**Comment by trotsiuk** [comment]
There is also from Georgios Xenakis https://github.com/drGeorgeXenakis/fr3PGD

**Comment by trotsiuk** [comment]
Maybe we can list them in the README file?

**Comment by florianhartig** [comment]
Why not, it might be useful for some, and it's also a gesture of appreciation to other developers.

**Comment by trotsiuk** [comment]
From Quinn Thomas https://github.com/EcoDynForecast/DAPPER

**Comment by florianhartig** [comment]
Hi Vova, I made a comment to clarify that our model differs from existing implementations, check if you find this appropriate https://github.com/trotsiuk/r3PG/commit/aa2b4cfd16d5bc878a7154c2383507ca216bab81

**Comment by florianhartig** [comment]
Also, I wonder if we should upload the MEE paper as a preprint? afaik this is no problem, and so we could already link to it. I prefer the arXiv, but I guess bioarXiv is also OK.

**Comment by trotsiuk** [comment]
I guess we can upload here, but it is too late to upload to e.g. arXiv. During MEE submission they ask if it was uploaded to some of those archives, and I marked as NO. If we will upload now, it will somehow violate my answer.

**Comment by trotsiuk** [comment]
Thanks for clarifying the Readmee. Now there are some errors in Travis build again :D

**Comment by florianhartig** [comment]
The message is 

`curl: (22) The requested URL returned error: 429 too many requests`

I think there is an overload somewhere at the toolchain - let's wait for next builds to see if the problem remains.

**Comment by florianhartig** [comment]
About the paper - I don't think it really helps / distributes it well to upload it here. You could write an email to Chris from MEE to ask him if it's a problem to still upload it, but if you think it's too much work we can also just skip it. I was just thinking about it as I was changing the text.

**Comment by trotsiuk** [comment]
Ok, I don't know how it really works with the Journals and arXiv, never done it before. Let's maybe just wait few days to know if it will go to review or will be rejected. In case of review I will write to editorial office and upload to arXiv. If rejected we can do whatever we want

**Comment by florianhartig** [comment]
OK, seems now the build works again, I will close this now. About preprint: it was just a suggestion. I have very good experiences with preprints, as long as one is transparent with the journal about it. It just means that your paper is visible 6-12 months before.
