### ISSUE TITLE
src/Makevars has  all: $(SHLIB) clean

### ISSUE THREAD

**Issue by florianhartig** [trotsiuk/r3PG#32]
See https://github.com/trotsiuk/r3PG/issues/23#issuecomment-627116337

```
Dear maintainer,
Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_r3PG.html>.
Please correct before 2020-05-26 to safely retain your package on CRAN.
The CRAN Team

src/Makevars has

all: $(SHLIB) clean

'Writing R Extensions' warned you that was wrong, and it leads to frequent failures with parallel makes.
```

I think this is one of their new checks (similar found here for [rstantools](https://github.com/stan-dev/rstantools/issues/71))

Ok, I think I have fixed it based on this [Fix for parallel make based on Brian Ripley](https://github.com/aadler/SimpFort/commit/e9aa218bdb25aadcdeafeb1a410a82b7c48a3c2c) and [this](https://www.avrahamadler.com/2018/12/09/the-need-for-speed-part-1-building-an-r-package-with-fortran/)

**Comment by florianhartig** [comment]
Hi @trotsiuk, sounds good to me. As we don't have a super tight deadline, we might as well use this revision to smoothen out a bit the package. I think it's sufficient if this is pushed back to CRAN in a few days, I don't think this will affect the average user.

**Comment by trotsiuk** [comment]
This is a good suggestion, I didn't thought about it in such a way. Yes, I will re-submitt is later, e.g. 2020-05-24.

**Comment by florianhartig** [comment]
@trotsiuk - side note: best practice for fixes like this is: create a new branch, do the fixes, create pull request with text that includes "fixes #32" or so, test pull request, when merged this will automatically close the respective issues.

**Comment by florianhartig** [comment]
> Yes, I will re-submitt is later, e.g. 2020-05-24.

I would do a few days earlier, as there may be other problems.

**Comment by trotsiuk** [comment]
Yep, we can do it in this way. We discussed it previously regarding branch vs direct pull, but I agree that now it is a good time to use brach.

**Comment by florianhartig** [comment]
One other question - I suppose we can't check if the fix works until we submit this to CRAN, right? Ot did the message also appear in the winbuilder checks?

**Comment by trotsiuk** [comment]
I couldn't reproduce this issue myself. win builder doesn't produce an error. The error is coming from  linux fedora clang. I now again run the `devtools::check()`, `devtools::check_rhub()`, `devtools::check_win_devel()`
