### ISSUE TITLE
Prepare 0.1.1 release

### ISSUE THREAD

**Issue by florianhartig** [trotsiuk/r3PG#33]
For comments about the next release

**Comment by florianhartig** [comment]
Hi Vova, I suppose we should push this update soon, right? I think we have nothing substantial to add soon, so why not push the update now, and then the things that are open have to go in 0.1.2.

**Comment by trotsiuk** [comment]
Yes, I plan to do it tomorrow.

**Comment by trotsiuk** [comment]
Done
https://github.com/trotsiuk/r3PG/releases/tag/v0.1.1
