### ISSUE TITLE
Debian Linux, R-devel BayesianTools issue

### ISSUE THREAD

**Issue by trotsiuk** [trotsiuk/r3PG#34]
Hi @florianhartig 

This is not really `r3PG` issue, but during the check on `Debian Linux` the error occur due to suggest library `BayesianTools`.

- ERROR build [with `BayesianTools`](https://builder.r-hub.io/status/r3PG_0.1.0.tar.gz-dac2111a016d4827b887944f07c87f55). Starting with package `mime` on line 1364

- OK build [without `BayesianTools`](https://builder.r-hub.io/status/r3PG_0.1.1.tar.gz-0b107ef45bf04f00b4b7acf118604b43)

I believe this is ok for CRAN, and for users? Or do you think it is better to remove those packages from `suggest`?

**Comment by florianhartig** [comment]
If it's not a requirement of CRAN, I would leave it for now. Very likely this is the same problem as https://github.com/trotsiuk/r3PG/issues/26 and it is through a chain of dependencies, 

BT -> DHARMa -> spaMM

where spaMM now requires a dependency that is not available per default on Linux. I have moved spaMM from import to suggest in the most recent update of DHARMa, I hope that this breaks the dependency problem for packages that depend on DHARMa

**Comment by florianhartig** [comment]
Just to clarify - this is what I would do if CRAN doesn't require us to fix this. If the problem remains with the next r3PG update, we could also remove BT. But I think it would be good style to keep packages that are important for examples in suggests. This would possibly also apply to other packages you use in the vignette btw., e.g. ggplot2, dplyr, although those are so common that one could argue about the trade-off of convenience of the user + and dependencies which can create trouble -

**Comment by trotsiuk** [comment]
I believe this should not be and issue for CRAN, as the package [check on Debian Linux](https://cran.r-project.org/web/checks/check_results_r3PG.html) is passed on CRAN. The only error occurs on fedora clang, which shall be ok after the [adjustment](https://github.com/trotsiuk/r3PG/commit/618e162ddf30f4d145d418b3589e302a1bd76496).

I would keep packages in `suggested` for now, and check it after re-submission
