### ISSUE TITLE
Remove vignettes_build?

### ISSUE THREAD

**Issue by florianhartig** [trotsiuk/r3PG#35]
Because now available on CRAN? I would only keep the data.

**Comment by trotsiuk** [comment]
I would still keep the `Rmd` file, as on CRAN we have only `HTML`. If we want to re-build the vignette, we need the `Rmd` again.

**Comment by florianhartig** [comment]
OK, sorry, I have forgotten that we moved this there because of the file size of the raw data. Makes sense to keep this folder, but I removed the .html, kept it in the ignore list, and added a readme that links to the CRAN vignette!
