### ISSUE TITLE
Roxygen old usage or not 

### ISSUE THREAD

**Issue by florianhartig** [trotsiuk/r3PG#4]
I added Roxygen: list(old_usage = TRUE) to the description, which means that parameters values in the help will not be separated by a linebreak - this is how it used to be in R.

Since the last Roxygen version, the changed this, but I prefer the old style. You can try for yourself what you like best

**Comment by trotsiuk** [comment]
I'm very fine with both versions. Was not even aware about it. Thank you for pointing.
