### ISSUE TITLE
provide the light absorption as an output

### ISSUE THREAD

**Issue by trotsiuk** [trotsiuk/r3PG#43]
from @DavidForrester 

would it be possible to provide the light absorption as an
output? I was looking at the par, I guessed this is photosynthetically
active radiation (as opposed the absorption of par), but if it was it would
be solar radiation / 2, and it would not vary between species. If it is the
absorbed par, it might be better to name it apar, which is often used, and
would distinguish it from par, which is also often used, but for
photosynthetically active radiation.

**Comment by trotsiuk** [comment]
Yes @DavidForrester  we can easily add more output variables. Currently we are outputting 
[`par`](https://github.com/trotsiuk/r3PG/blob/09784bb8831e07fc1c6f5a7e4b3489eb281fced3/pkg/src/i_write_out.h#L75) which is calculated from the `layer par` in case of 3PGmix version.

[`parl(:) * lambda_h(:) * lambda_v(:)`](https://github.com/trotsiuk/r3PG/blob/09784bb8831e07fc1c6f5a7e4b3489eb281fced3/pkg/src/md_3PG.f95#L1399)

Please, describe more what shall be adjusted or renamed and I can implement it.

**Comment by DavidForrester** [comment]
Great. I see now. I think the "par" could just be renamed to "apar".
Similarly, the apar of the layer "parl" could be called "aparl".

i.e. apar(:) = aparl(:) * lambda_h(:) * lambda_v(:)
