### ISSUE TITLE
spatial simulation in vignette broken with multidplyr 0.1.0

### ISSUE THREAD

**Issue by twest820** [trotsiuk/r3PG#47]
multidplyr's change from `create_cluster()` to `new_cluster()` came up already in #40. There are also updates needed with `cluster_copy()` and `partition()`.

The code below hello worlds for me with r3PG 0.1.3 and multidplyr 0.1.0, though there are warnings about differing measure variable attributes and uneven raster pixels and there is probably a reliability issue within multidplyr as the R session crashed the first time I tried the code. The uneven pixels appear to be due to the site locations in coord.grid and are presumably not a new issue.
```r
cl_in <- new_cluster(n = 2) %>% # or more cores if desired
  cluster_library(c('r3PG', 'purrr', 'dplyr', 'tidyr')) %>%
  cluster_copy(names = c("r3pg_grid", "species.grid", "thinn.grid", "param.draw"))

sim.grid <- inner_join(site.grid, climate.grid, by = 'grid_id')  %>%
  sample_n(10) %>%
  group_by(grid_id) %>% # partition() now operates on the tibble's groups
  partition(cluster = cl_in) %>%
  mutate( out = map2(site, forc, ~r3pg_grid(.x, .y))) %>%
  select( grid_id, out) %>%
  collect() %>%
  unnest_legacy() %>%
  ungroup()
```

**Comment by trotsiuk** [comment]
Thank you @twest820 for bringing this issue.

The vignette shall be updated in the development version `0.1.4` or r3PG.

You are correct regarding the warning on `irregular pixels...`. This is due to the fact that some grid-cells are missing which case this warning during the raster plotting.
