### ISSUE TITLE
How to set up 3pg for mixed forests?

### ISSUE THREAD

**Issue by florianhartig** [trotsiuk/r3PG#48]
Question from a user: 

> I would like to assess the contribution of [redacted] Forest ( A mixed forest of Cedar and Oak) to carbon sequestration efforts using the 3PG model.
> 
> Forest stands in [redacted] Forest do not have the same age nor the same structure. In some locations stands are pure ( containing only one species), in other locations, stands are mixed. Also, In some locations cedar is dominant, in other locations Oak is the dominant. Thus, I think that I could not use the same species input dataframe in order to predict my dependent variable which is NPP.

**Comment by florianhartig** [comment]
Hi, in principle, the setup to run a single 2-species mixed forest stand is described in the vignette https://cran.r-project.org/web/packages/r3PG/vignettes/r3PG-ReferenceManual.html

If you want to run multiple stands with different starting conditions / dominance / mixtures, I would just create a loop during which you

- create a respective input file 
- run the model
- collect outputs

similar to what we do in https://cran.r-project.org/web/packages/r3PG/vignettes/r3PG-ReferenceManual.html#spatial-simulations in the Vignette.

**Comment by trotsiuk** [comment]
@florianhartig has nicely described the requirements and examples for the `r3PG`. To shortly add on that:

- **input**  shall be in the same format as provided in the vignette. In particular one shall provide data.frame for site, species, climate, thinning, and parameters (more see `?r3PG::prepare_input`). This input shall correspond to particular forest structure, desired for simulations. It is not appropriate use the default provided in the R package. For each new simulation one need to prepare his own input.

- **parameters** this is one of the most important part for the new type of forest. For this particular case, it would be important to prepare the parameters set for Cedar and Oak. While for Oak one can use the previously published, for Ceder there is a need to either use a default or develop a new parameters set.
