### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by florianhartig** [trotsiuk/r3PG#5]
at the moment, all settings have to be provided, right?

```
settings = list(light_model =
  1, transp_model = 1, phys_model = 1, correct_bias = 0, calculate_d13c = 0)
```

could also implement a function like in BT which checks settings. I have done this for another model, which is, however, not public. Can send you an example. However, not really a priority.

**Comment by florianhartig** [comment]
p.s.: same for parameters

**Comment by trotsiuk** [comment]
No, they don't need to be provided. It is only for the example. You can leave them empty. 

There is function for settings and parameters that check and replace

**Comment by florianhartig** [comment]
Ah, OK, then I will clarify this in the help
