### ISSUE TITLE
3PG model is insensitive to parameter variation (Morris Sensitivity Analysis)

### ISSUE THREAD

**Issue by Catarinaxa** [trotsiuk/r3PG#50]
Dear,

I'm trying to analyze the sensitivity of my 3PG model using the Morris method as it was described in the vignette example.
But I got as result of analysis a dataframe full of 0, meaning that the model is non sensitive to parameter variation values.

So basically the species I'm working on is Cedrus atlantica Manetti (Blue cedar) for which no model has been developed before. To get around the lack , I decided to use "param_solling" ( default, min and max values). 

Also , biomass ( stem, foliage and roots) , DBH and NPP were used to calculate log likelihood. [ NPP for the entire period month by month , and for the other variables the begining and the end of the period ].

When I calculated log likelihood value using default parameters I got -915. But  the model seems to be insensitive to parameter variation.

Is there any issue with the approach ? 

Any help will be appreciated.

Catarina S.

NB : we are working on the same project me and the user who asked the precedent question @issamyax

[placette70.xlsx](https://github.com/trotsiuk/r3PG/files/6371912/placette70.xlsx)

**Comment by florianhartig** [comment]
Hi Catarina, could you post a reproducible example of this? See [here](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example) for tips on how to make a reproducible example.

**Comment by Catarinaxa** [comment]
Thank you for you attention Dear @florianhartig 

` 
# load packages
library(r3PG)
library(dplyr)
library(ggplot2)
library(tidyr)
library(purrr)
library(BayesianTools)
library(sensitivity)




# data loading ( placette70.xlsx and solling.rda  are respectively an excel and rda files joint )
F_site <- read_excel("placette70.xlsx",sheet = 'site')
F_species <- read_excel("placette70.xlsx", sheet = 'species')
F_climate <- read_excel("placette70.xlsx", sheet = 'climat')
F_error <- read_excel("placette70.xlsx", sheet = 'error')
F_observ <- read_excel("placette70.xlsx", sheet = 'obs')
load(file = "solling.rda")

@convert F_observ from dataframe to list 
F_observ <- t(do.call(rbind, lapply(F_observ, as.numeric)))

r3pg_sim <- function( par_df, ...){
  #' @description function to simulate the model for a given parameter
  #' @param par_df data frame of the parameters with two columns: parameter, piab
  
  sim.df <- run_3PG(
    site = F_site, 
    species = F_species,
    climate = F_climate,
    thinning = NULL,
    parameters = par_df, 
    size_dist = NULL,
    settings =  list(light_model = 1, transp_model = 1, phys_model = 1),
    check_input = TRUE, ...)
  
  return( sim.df )
}


r3pg_ll <- function( par_v ){
  #' @param par_v a vector of parameters for the calibration, including errors 
  #' par_v = par_cal_best
  
  # replace the default values for the selected parameters
  err_id = grep('err', par_cal_names)
  
  par_df = data.frame(parameter = par_cal_names[-err_id], piab = par_v[-err_id])
  err_v = par_v[err_id]
  
  # simulate the model
  sim.df <- r3pg_sim(par_df, df_out = FALSE)
  sim.df[,,6,2][1]<-0
  sim.df <- cbind(sim.df[,,6,2],sim.df[,,2,5], sim.df[,,4,c(1,2,3)])
  
  # calculate the log likelihood
  logpost <- sapply(1:5, function(i) {
    likelihoodIidNormal( sim.df[,i], F_observ[,i], err_def[i] ) 
  }) %>% sum(.)
  
  if(is.nan(logpost) | is.na(logpost) | logpost == 0 ){logpost <- -Inf}
  
  return( logpost )
}   
     # default parameters
par_def <- setNames(param_solling$default, param_solling$param_name)
err_def <- setNames(F_error$default, F_error$param_name)
     
      # parameters for calibration and their ranges
param_morris.df <- bind_rows(param_solling, F_error) %>% filter(!is.na(min))
par_cal_names <- param_morris.df$param_name
par_cal_min <- param_morris.df$min
par_cal_max <- param_morris.df$max
par_cal_best <- param_morris.df$default
       
r3pg_ll( par_cal_best)


morris_setup <- createBayesianSetup(
  likelihood = r3pg_ll, 
  prior = createUniformPrior(par_cal_min, par_cal_max, par_cal_best), 
  names = par_cal_names)

set.seed(432)
morrisOut <- morris(
  model = morris_setup$posterior$density,
  factors = par_cal_names, 
  r = 500, 
  design = list(type = "oat", levels = 20, grid.jump = 2), 
  binf = par_cal_min, 
  bsup = par_cal_max, 
  scale = TRUE)

# summarise the moris output
morrisOut.df <- data.frame(
  parameter = par_cal_names,
  mu.star = apply(abs(morrisOut$ee), 2, mean, na.rm = T),
  sigma = apply(morrisOut$ee, 2, sd, na.rm = T)
) %>%
  arrange( mu.star )





morrisOut.df %>%
  gather(variable, value, -parameter) %>%
  ggplot(aes(reorder(parameter, value), value, fill = variable), color = NA)+
  geom_bar(position = position_dodge(), stat = 'identity') +
  scale_fill_brewer("", labels = c('mu.star' = expression(mu * "*"), 'sigma' = expression(sigma)), palette="Dark2") +
  theme_classic() +
  theme(
    axis.text = element_text(size = 6),
    axis.text.x = element_text(angle=90, hjust=1, vjust = 0.5),
    axis.title = element_blank(),
    legend.position = c(0.05 ,0.95),legend.justification = c(0.05,0.95)
  )
`


I remain at your disposal for any further information.

With regards,

Catarina S.

[solling.zip](https://github.com/trotsiuk/r3PG/files/6371998/solling.zip)

**Comment by trotsiuk** [comment]
Dear @Catarinaxa 

Thank you for the interest in using the `r3PG` mode. 

The issue is coming from the `piab = par_v[-err_id])`. The parameter data-frame operate on column names. Currently you are changing the parameters for the `piab` species, but not for Cedrus.

My recommendation would be to 
- change the `cedrus atlantica` in the `F_species` to `cedrus` (would suggest to avoid spacing)
- change `piab = par_v[-err_id])` to `cedrus = par_v[-err_id])`

To check if it works, you shall get different results with:

```
r3pg_ll( par_cal_best)
r3pg_ll( par_cal_min)
r3pg_ll( par_cal_max)
```

as result you shall receive something similar to below figure

![image](https://user-images.githubusercontent.com/15097779/116065772-a42adb80-a687-11eb-9fdf-513a4286e4c1.png)

**Comment by Catarinaxa** [comment]
Dear @florianhartig 

Many thanks to the team for developing such a wonderful 3PG mode having such a reactive community.
