### ISSUE TITLE
growth is negligible if trees are planted more than one or two months after simulation starts

### ISSUE THREAD

**Issue by twest820** [trotsiuk/r3PG#52]
While I haven't looked through the code to see where this issue is coming from, there appear to be some assumptions about the relationship between d_site$from and d_species$planted. If from is too far before planted then the trees don't grow.

There's a few curious things here:

- stems_n at the beginning of the stand output matches the number of stems planted even though no trees have been planted.
- GPP is small but nonzero (~1E-8) before planting and then declines after planting, resulting in GPP being too low by several orders of magnitude by a couple decades into the stand trajectory. This carries through into NPP and explains the lack of growth.
- The above behavior doesn't occur if from precedes planted by one or two months but whether the maximum difference before growth shuts down is one or two months seems to vary seasonally. Not sure if there's a requirement from and planted be in the same year or if something else is going on.
- From can occur after planting, in which case the trees sit in stasis until timesteps start. This is unsurprising from a code perspective but, since there doesn't appear to be any constraint on the lag to simulation start, it's possible to skip decades of growth.

The workaround I'm using is to set from = planted, which is no trouble for my purposes, but I wanted to capture this since it seems like there's some missing argument checking, maybe some bugs, and others might find it harder to troubleshoot the issue. Not sure if the vignette should have from and planted getting initialized by a shared variable or one picking up its value from the other, but either coding method would discourage their divergence.

I also wonder if these apparent issues around triggering planting as a management action from a specific date might partially or fully explain #36.

**Comment by trotsiuk** [comment]
Thank you @twest820 for submitting the issue.

If understood you correctly, in your issue there are no growing species at the time of the simulation start? 

In the r3PG simulation shall start the earliest month when one of the species is growing (this was also in the old version).

You can consider submitting the reproducible to have a look on it.

**Comment by twest820** [comment]
That's correct. I took a quick look at the code and am not seeing the issue. I also don't get repro with a quick modification of the vignette.

I can see about packing down what I'm working on into a reproducible. Would it be OK if I emailed that to you?

**Comment by trotsiuk** [comment]
Yes, sure, feel free to mail. But it generally better to keep communication here, so it is available also for other users.

**Comment by twest820** [comment]
Cool. Agree on the communication default. However, I suspect the cost of producing a fully anonymized reproducible which can be world visible here would exceed its benefits. I've several other things I'm working on at the moment, so it'll probably be a while just to reduce it to something emailable.

**Comment by trotsiuk** [comment]
Hi @twest820 I'm slowly revisiting some issues. Wonder wether we shall continue on this one and if you can provide the example as mentioned above?

**Comment by twest820** [comment]
Hi, from a quick look the exact test in
```
            ! Add new cohort ----------------------------------------------------------------------
            where (age(ii,:) .eq. 0.d0 )
              stems_n(:) = stems_n_i(:)
              biom_stem(:) = biom_stem_i(:)
              biom_foliage(:) = biom_foliage_i(:)
              biom_root(:) = biom_root_i(:)
            end where
```
is going to be unreliable since `age` is floating point. So checking to see if the planting action isn't triggering due to lack of accommodation for numerical precision seems a good starting point.

Also, the initialization line
```
age_m(1,i) =  age(1,i)
```
is odd. Since `age_m` and `age` have different units (months and years) `age_m(1,i)` gets set to an incorrect value except in the special case where `age(1,i)` is zero.

From a design perspective, an argument could be made for removing `age` and making `age_m` an integer—in most places where `age` is used it's subject to numerically fragile exact tests for non-negativity (`age .ge. 0`) or positivity (`age .gt. 0`) which can result in the first month of output getting skipped (and maybe NaN rather than -Inf in bias correction, though that's likely pretty minor). There's also slight structural biases in the current initialization calculations as it's assumed all 12 months are equally 30.42 days long.

**Comment by trotsiuk** [comment]
Hi, I made a two examples of the species being planted after the start of the simulations. In both cases no error has occurred (see below for the reproducibility). In case there is an re-ocuring issue on your side please send the example, this will much help to debug the code.

```
# Library
library(r3PG)
library(dplyr)
library(ggplot2)
````
### One species present before start of simulation

```
d_species_1 <- d_species

d_species_1$planted[2] <- "2002-06"
d_species_1$stems_n[2] <- 1600
d_species_1$biom_stem[2] <- 3
d_species_1$biom_root[2] <- 1
d_species_1$biom_foliage[2] <- 2

out_3PG <- run_3PG(
  site        = d_site,
  species     = d_species_1,
  climate     = d_climate,
  thinning    = d_thinning,
  parameters  = d_parameters,
  size_dist   = d_sizeDist,
  settings    = list(light_model = 2, transp_model = 2, phys_model = 2,
                     height_model = 1, correct_bias = 0, calculate_d13c = 0),
  check_input = TRUE, df_out = TRUE)

i_var <- c('age', 'stems_n',  'dbh',  'biom_stem', 'biom_root', 'biom_foliage')
i_lab <- c('Age species', 'Stem density', 'DBH', 'Stem biomass', 'Root biomass', 'Foliage biomass')

out_3PG %>%
  filter(variable %in% i_var) %>%
  mutate(variable = factor(variable, levels = i_var)) %>%
  ggplot( aes(date, value))+
  geom_line( aes(color = species), size = 0.5)+
  facet_wrap( ~ variable, scales = 'free_y', ncol = 3,
              labeller = labeller(variable = setNames(i_lab, i_var) )) +
  scale_color_brewer('', palette = 'Dark2') +
  theme_classic()+
  theme(legend.position="bottom")+
  xlab("Calendar date") + ylab('Value')
```

![image](https://github.com/trotsiuk/r3PG/assets/15097779/5b87ee45-515c-40a7-b6df-f7d0b36fd14e)

### No species present before simulation

```

d_species_2 <- d_species

d_species_2$planted <- "2002-06"
d_species_2$stems_n <- 1600
d_species_2$biom_stem <- 3
d_species_2$biom_root <- 1
d_species_2$biom_foliage <- 2

out_3PG <- run_3PG(
  site        = d_site,
  species     = d_species_2,
  climate     = d_climate,
  thinning    = d_thinning,
  parameters  = d_parameters,
  size_dist   = d_sizeDist,
  settings    = list(light_model = 2, transp_model = 2, phys_model = 2,
                     height_model = 1, correct_bias = 0, calculate_d13c = 0),
  check_input = TRUE, df_out = TRUE)

i_var <- c('age', 'stems_n',  'dbh',  'biom_stem', 'biom_root', 'biom_foliage')
i_lab <- c('Age species', 'Stem density', 'DBH', 'Stem biomass', 'Root biomass', 'Foliage biomass')

out_3PG %>%
  filter(variable %in% i_var) %>%
  mutate(variable = factor(variable, levels = i_var)) %>%
  ggplot( aes(date, value))+
  geom_line( aes(color = species), size = 0.5)+
  facet_wrap( ~ variable, scales = 'free_y', ncol = 3,
              labeller = labeller(variable = setNames(i_lab, i_var) )) +
  scale_color_brewer('', palette = 'Dark2') +
  theme_classic()+
  theme(legend.position="bottom")+
  xlab("Calendar date") + ylab('Value') +
  scale_x_date(limit=c(as.Date("2001-01-01"),as.Date("2010-11-30")))

```

![image](https://github.com/trotsiuk/r3PG/assets/15097779/928e821c-31a6-43f1-bb66-4b03dae905a3)
