### ISSUE TITLE
vignette passes a default standard deviation vector to likelihoodIidNormal

### ISSUE THREAD

**Issue by twest820** [trotsiuk/r3PG#54]
The signature of [`likelidhoodIidNormal`](https://www.rdocumentation.org/packages/BayesianTools/versions/0.1.7/topics/likelihoodIidNormal) is 

```likelihoodIidNormal(predicted, observed, sd)```

but the vignette has

```
  err_def <- setNames(error_solling$default, error_solling$param_name)

  logpost <- sapply(1:6, function(i) {
    likelihoodIidNormal( sim.df[,i], observ_solling_mat[,i], err_def[i] ) 
  }) %>% sum(.)
```

I have three concerns about this.

1. It's unclear where the default values come from. Since the other columns in `error_solling` are `min` and `max` and `default` is always in between it looks like the intent might be to have some sort of constrained error model. But `min` and `max` don't seem to be used and I'm not seeing as much of a connection between `default` and the data as I would expect. For example, `err_biom_root` and `err_biom_foliage` both default to 1 even though root biomass sims out is several times larger than foliage biomass and is usually considerably harder to measure than foliage biomass.
2. It's implausible the covariance matrix is diagonal. I recognize r3PG is limited to what BayesianTools supports and that there is no `likelihoodNormal(predicted, observed, covariance)` available. But treating error in basal area, height, and stem biomass as independent of error in DBH leaves me less confident in the accuracy of Morris and DE-MCMC results than I would like. I don't see an issue tracking this in either r3PG or in the BayesianTools repo, so wanted to capture it.
3. The name `likelihoodIidNormal` implies a scalar standard deviation but r3PG is passing in a vector that's definitely not indicating identical distributions. I would therefore expect the r3PG vignette to fail in parameter validation on the BayesianTools side. But it doesn't. Since the BayesianTools documentation is terse it's unclear if there's vector support (suggesting `likelihoodIidNormal` is probably an obsolete name) or if something like the default standard deviation for `err_basal_area` getting applied to all six measurements.

@florianhartig, if you'd like a tracking issue for 2 or 3 on the BayesianTools side let me know and I can type something up.

**Comment by trotsiuk** [comment]
Dear @twest820 

Thank you for the pointing out.

1. Indeed, there was a typo in the code, the correct version is
```
  logpost <- sapply(1:6, function(i) {
    likelihoodIidNormal( sim.df[,i], observ_solling_mat[,i], err_v[i] ) 
  }) %>% sum(.)
```
Where the `err_v` is a vector with error for each of the observation value and is passed through the Morris analysis as a value from min-max range (similarly later in the calibration).


3. This is not one standard deviation, but the vector of deviations (one for each of the observation variable).

**Comment by twest820** [comment]
Thanks @trotsiuk! `err_v` makes considerably more sense (for folks who might be reading this without having looked at the code, the change from `err_def` to `err_v` makes the standard deviations of the multivariate normal distribution MCMC parameters under uniform priors set by `error_solling$min` and `max` rather than fixing an invariant distribution).

2. It doesn't look like an involved code change to extend the `err_v` approach to off diagonal elements of the covariance matrix using, say, [`dmvnorm`](https://www.rdocumentation.org/packages/mvtnorm/versions/1.1-2/topics/Mvnorm). I haven't tried it yet, though, so don't have a sense of convergence or performance.
3. I pulled the code for `likelihoodIidNormal`. `sd` flows to `dnorm`. The `dnorm` docs don't quite say what it does with a vector `sd` but a quick check shows it behaves like `rnorm` with a vector `sd`. So  `likelihoodIidNormal` is operating as `likelihoodIndependentNormal` in this use.
```r
likelihoodIidNormal <- function(predicted, observed, sd){
  notNAvalues = !is.na(observed)
  if (sd <= 0) return (-Inf)
  else return(sum(dnorm(predicted[notNAvalues], mean = observed[notNAvalues], sd = sd, log = T)))
}
```

I noticed all values of `error_solling$min` are zero but `if(sd <= 0)` in `likelihoodIidNormal` will check only the first element, allowing a NaN likelihood if any of `sd[2:n]` are zero. This is OK for code function since `r3pg_ll` will turn it to `-Inf`. It does bring up a minor mathematical issue in that the standard deviations' priors should probably have small but nonzero lower bounds. This is perhaps more of a philosophical consideration than a functionally significant one.

**Comment by trotsiuk** [comment]
Thanks @twest820 for additional testing and information! Nice to see that you are interested. Maybe @florianhartig will comment more on it, as he is more in charge of `BayesianTools`.

As a side comment, the `BayesianTools::likelihoodIidNormal()` was chosen as a ready to go example for the vignette. However, it is advisable to construct a more specific `likelihood` function for the particular user analysis. Specifically in relation to uncertainties of the observational data (e.g. biomass estimations , etc)

**Comment by florianhartig** [comment]
Hi Todd,

thanks for reporting the typos. From the BT side, I don't really see an issue - the function is fully document and does what it says, i.e. it implements an iid normal likelihood, i.e. you have a vector of observations / predictions and exactly ONE sd value. 

The different sds in the vignette are not per observation, but per data type (which is basal area, dbh, height, stem biomass, foliage biomass, and root biomass). 

So what we assume here is that each data type in itself is iid normal, error for different data types are independent, and potentially have a different sd.

**Comment by florianhartig** [comment]
p.s.: I don't think a prior including zero is a problem, as the likelihood automatically evaluates -Inf for any non-sensible value of the sd. I think it's more sensible to exclude zero in this way that to set an arbitrary minimum.

**Comment by florianhartig** [comment]
pps: you can of course include all kind of covariances in the likelihood if you want to. As Vova said, the iidnorm likelihood in BT is just a convenience function to allow us to write cleaner / simpler examples for teaching. That being said, the challenge when doing this is to make it computationally fast - multivariate normal distributions are costly to evaluate. We have an AR1 likelihood for temporal autocorrelation available that is fast https://florianhartig.github.io/BayesianTools/reference/likelihoodAR1.html but for everything else, you will probably want to work with sparse matrices as often as possible.

**Comment by twest820** [comment]
> Thanks @twest820 for additional testing and information!

You're welcome. Given MCMC's tendency to arrange model parameters to reproduce the specified error distribution, I suspect the research question of what error distributions are most appropriate is one which will be with us for some time. From a package standpoint, most users will probably just be wanting to calibrate 3-PG to their sites and not thinking too deeply about likelihood construction. So whatever the vignette does has a good chance of influencing people's results.

Given the current package version is 0.1.3 and what I know of the state of investigations into MCMC error models, it's my sense a multivariate normal's an entirely reasonable default. I would also suggest helping users move away from inaccurate assumptions about independence between data types (as @florianhartig just called it) would, in this case, be part of package maturity. But that's just a suggestion; it's not my package.

> multivariate normal distributions are costly to evaluate

Yes, `dmvnorm` calls `backsolve` so I assume it's O(N³). In a forestry context I think there's a good chance of tractability since even a fairly lightweight stand-level growth model such as 3-PG is expensive to evaluate compared to a multivariate normal. With current datasets a stand level calibration frequently means there's only short time series of TPH, BA, and QMD to consider. With maybe a few values of H₁₀₀ or some other top height from LiDAR. So **Σ** is likely to be just 3x3 or 4x4.

As I said above, though, I haven't profiled.

Thanks for mentioning `likelihoodAR1`. I'd seen it earlier and just looked at the code but [http://stat.unicas.it/](http://stat.unicas.it/) isn't responding at the moment. From how the formula is, it looks like `predicted` and `observed` are time series vectors. There's an asymmetry in the use of `res`, so I'm guessing they should be ordered with `predicted[1]` and `observed[1]` being the longest ago values in the series and `predicted[-1]` and `observed[-1]` being the most recent.

Not sure if you've talked about this with Volodymyr and David but what I usually see is AR(1) or maybe ARMA(1,1) have the best ΔAIC support on annual tree growth series. More frequent measurements are uncommon and in many areas it's normal to have measurement intervals of 5-10 years on regularly remeasured permanent plots. These intervals are also frequently uneven since, sooner or later, something will come up and delay a measurement by a year or more and lapses in funding mean skipped measurements. So, even though these are time series, it's often questionable whether data points are close enough together in time to be autocorrelated and the irregular spacing means they're not readily admissible to most time series methods.

> you have a vector of observations / predictions and exactly ONE sd value.

Well, this does mean it's a code defect that the r3PG vignette is able to pass a vector `sd` without an error. :smiley: Easy argument check to add, though. R's loose typing has some advantages but this isn't one of those times.

> I don't think a prior including zero is a problem, as the likelihood automatically evaluates -Inf for any non-sensible value of the sd.

Only if the caller adheres to the unenforced contract of a scalar `sd` (though a vector `sd` also meets IID if all the elements are the same). Which `r3pg_ll` doesn't, hence my mentioning about it being able to get itself in trouble. In integration like this it's almost always the case reasonable changes exist on both sides. I'm a third party here, though, so I think I stop with understanding what the issue is. Thanks again for the comments.

**Comment by trotsiuk** [comment]
>From a package standpoint, most users will probably just be wanting to calibrate 3-PG to their sites and not thinking too deeply about likelihood construction.
I would also suggest helping users move away from inaccurate assumptions about independence between data types

The aim of the package is to have the 3-PG model available through the R environment, and not a full calibration of the model. The vignette provide the test example for the calibration, but this in NOT part of the `r3PG` package. 
I would still argue that each user is responsible himself for implementing any type of calibration, and design of the likelihood function.

>you have a vector of observations / predictions and exactly ONE sd value.

For each vector of observation/predictions type there is ONE sd value, but when using multiple observations/prediction during calibration we are passing the vector of sd `err_v` each element of which corresponds to particular observation/prediction. Again, this is NOT part of `r3PG` and there is no reason for checking it. User shall design his own LL function.

> Which `r3pg_ll` doesn't, hence my mentioning about it being able to get itself in trouble

This is the simplest example used for the vignette. As mentioned, user keeps responsibility for using and designing the LL function.

**Comment by florianhartig** [comment]
Hi Todd,

OK, first of all, I have many sympathies for the quest of checking assumptions of likelihoods etc. I think we have to separate a bit the issues though. In this context, I would first point out that at least 3 packages are involved:

1) r3PG, maintained by @trotsiuk, which implements the 3PG forest model 
2) BayesianTools, maintained by me, which implements primarily MCMC samplers (and not likelihoods, these were really just for convenience) for Bayesian computation
3) DHARMa, also maintained by me, which implements residual checks for frequentist and Bayesian statistics 

I agree with @trotsiuk that it is not the purpose of the r3PG vignette to explain in detail how to calibrate a forest model. We could maybe extend the BT vignette, and we had worked on such an extension in the past, but as you can imagine this is extremely time consuming, as there are countless other issues that can arise besides potential correlations between data types.

In general, the approach that I would suggest, and that we have taught in the past is: 

- Calibrate a model with a base likelihood (e.g. the one here)
- Analyze residuals for problems (including cross-correlations)
- Fix problems as you would for any other statistical model 

When working with real data, the most pressing problem is usually first of all to model the error, i.e. with real data you nearly always find heteroskedasticity and non-normal distributions. If that is solved, you can care about correlations. Also, there is the problem of how to deal with model error, see Oberpriller, J., Cameron, D. R., Dietze, M. C., & Hartig, F. (2021). Towards robust statistical inference for complex computer models. Ecology Letters, 24(6), 1251-1261. https://onlinelibrary.wiley.com/doi/full/10.1111/ele.13728

Again, all important issues, but it seems to me that these are outside each single R package, and would rather require a tutorial paper on how to calibrate computer models. 

@trotsiuk - we could add some comments in the vignette though to the effect that this is of course a base likelihood and should not be used for real data without checking?

**Comment by twest820** [comment]
> I agree with @trotsiuk that it is not the purpose of the r3PG vignette to explain in detail how to calibrate a forest model.

Me too, which is why I was careful to separate research questions from assisting users in making effective use of the package earlier.

I noticed issues 1-3 here because r3PG has, at least in my view, accomplished its purpose of making 3-PGpjs 2.7 and 3-PGmix available within R. Since vignettes are distributed with packages and usually serve as their primary set of examples, I'm failing to follow the reasoning the vignette is not part of the package. On a lines of code basis, I'm getting 88% of the vignette devoted to MCMC calibration of 3-PG, which seems consistent with currently published papers using r3PG.

Reducing the r3PG-MCMC association by refactoring among packages isn't something I've an opinion on. Whatever makes y'all happy. For my part, I'm happy I don't have to code 3-PG and MCMC myself, so thank you to both of you for going to the effort to make your work available within R and providing an indication of how to put the two together.

> Also, there is the problem of how to deal with model error

Ja. Nice intro. The bit in the discussion about statisticians and modelers is consistent with my experience, too. My sense as a forest biometrician is structural accuracy has received substantial attention in forest model development but formal efforts to measure and correct structural error occur primarily in the inspection of residuals of regression-based models. We all know the ecological fallacy and that regional calibrations are incorrect at the site level but, to my knowledge, r3PG+BayesianTools provides a uniquely accessible data assimilation path for doing something about that.

**Comment by twest820** [comment]
Follow on comment: I've had a chance to measure errors on some of my models and stem count, top height (H100), QMD, and basal area have correlation > 0.85. So good support for a dense, rather than diagonal, **Σ** in these stands. For a symmetrical 4x4 **Σ** that's a 10 parameter covariance model rather than four variance parameters for a diagonal **Σ**.
