### ISSUE TITLE
Automatic ecological sensibility checks / unit tests

### ISSUE THREAD

**Issue by florianhartig** [trotsiuk/r3PG#59]
Another thing I was thinking: would it be useful to try to automatise something like https://www.sciencedirect.com/science/article/pii/S0378112721003595 in the unit tests, such that we automatically check if future model versions / parameterisations still produce reasonable results?

**Comment by trotsiuk** [comment]
On this I'm not fully sure. Do you mean that we have a certain ranges of potential growth for a given site, and we make a unit tests for that? Currently we make a unit test if model gives the same output as desired.
