### ISSUE TITLE
Webpage

### ISSUE THREAD

**Issue by florianhartig** [trotsiuk/r3PG#6]
Why is https://trotsiuk.github.io/r3PG/ different from the readme? It's usually easier to maintain if this is just identical. 

https://trotsiuk.github.io/r3PG/ looks better to me than the readme.

**Comment by trotsiuk** [comment]
Why different? It is the same page. This is GitHub rounding of the readme file

**Comment by trotsiuk** [comment]
If you fully replace the readme file I would suggest to keep the stable link to the vignette at least. Was on line 12

**Comment by trotsiuk** [comment]
And what was the reason to fully replace the readme to the old version?

**Comment by florianhartig** [comment]
Sorry, my mistake. I had previously changed the readme, wanted to commit it, overwrote your readme, and I realized this, and thought I had reverted it, but accidentally reverted my other commit, after which I thought the files don't match :D

**Comment by florianhartig** [comment]
I think now all is back, and they are matched, all good, sorry.
