### ISSUE TITLE
Site and species specific fertility

### ISSUE THREAD

**Issue by trotsiuk** [trotsiuk/r3PG#61]
### Original question

We would like to use the "r3PG" package to test the validity for Lower Saxonia and Hesse and compare the predictions with our GAM models. Our models use quite some site specific data such as plant available water and nutrient levels. In 3PG both values are possible to set.

The problem we face is the fact, that the value for the nutrients is in the r3PG package located in 'd_species' and not (as expected) in 'd_site'. As in the example in the paper, modelling spatially explicit results (.grid), we would like to set an individual "Fertility rating" for each site instead of for the species in general.

Do you have an idea how to implement this in the R-package?

**Comment by trotsiuk** [comment]
The fertility 'nutrients’ are located at ‘d_species’ table. This is particularly designed in this way, since different species can have different fertility at the same site. E.g. for the cite A, Fagus sylvatica can have fertility o.7 and Pinus sylvestris only 0.5. Therefore, it would not be possible to set those values at the cite level.
If I understood your request correctly, you can specify different fertility for different sites by allocating it into d_species. For each site you can have a different d_species table which will indicate which fertility shall be used.

**Comment by trotsiuk** [comment]
### Follow up question

I worked my steps through the vignette and tried to understand the connection between size and species as you indicated that I could have a an entry in 'd_species'.

But how does the program knows which site is using which entry in the d_species table?

I went through the "Spatial simulations" section in the vignette and could not figure out how this connection is established.

What I found out so far:

```
climate.grid
# A tibble: 18,750 × 2
```

but

```
param.draw
# A tibble: 504 x 2
```

which is not a multiple of climate.grid

I am stuck, could you send me an example on how to implement this?

Btw, the vignette is not working with regard to the "multidplyr" library. I guess the library has changed. My code looks now like this:

-------
> cl_in <- new_cluster(n = anz) %>%
>    cluster_library(c('r3PG', 'purrr', 'dplyr', 'tidyr')) %>%
>    cluster_copy( "r3pg_grid" ) %>%
>    cluster_copy( "species.grid" ) %>%
>    cluster_copy( "thinn.grid" ) %>%
>    cluster_copy( "param.draw" )
-------

What has changed:
1. new_cluster instead of create_cluster
2. in cluster_copy the names have to be quoted.

**Comment by trotsiuk** [comment]
1. the function `run_3PG` is run for only one site at the time. Therefore, the information provided in the `site` and `species` will be used at that time.

There are few approaches how to run the simulation for multiple sites. The basic approach would be to use
```
for ( s in sites){
run_3PG(
...
}
```

In the example of the vignette we are using the nested tible where we have `site.grid` where each rows corresponds to one site. So then if you also want to have a different species fertility it is possible to provide a `species` table where each nested row corresponds to the one site (within nested row you can have multiple species).

2. Indeed, there was a change in `multidplyr` library as mentioned here #47  and #40 . The vignette was updated in that time and the most actual valid vignette is always available [here](https://htmlpreview.github.io/?https://github.com/trotsiuk/r3PG/blob/master/pkg/vignettes/r3PG-ReferenceManual.html)  (you can also access it through the main page of the [`r3PG`](https://github.com/trotsiuk/r3PG) )

**Comment by rbialoz** [comment]
Thank you for your comments. According to my initial question about how to incorporate different 'fertilities' for each site 
I realised that this line from the vignette:

sim.grid <- inner_join(site.grid, climate.grid, by = 'grid_id')

should be the solution. I need to construct a species.grid tibble having the 'grid_id' in the first place (like in site.grid) and construct a new 

r3pg_grid <- function(site, species, forc) { ... }

which takes the appropriate species entry for that site.
