### ISSUE TITLE
How to manage external contributions that may be provided from a group at  KIT?

### ISSUE THREAD

**Issue by florianhartig** [trotsiuk/r3PG#62]
Hi @trotsiuk / @DavidForrester,

I though it's easiest to discuss this via an issue - I had mentioned at least to Vova that there is a group at KIT who is planning to use r3PG for an applied project that they have on doing some forestry predictions. The technical person in charge is @Rasilgon (Ramiro).

For the project, Ramiro is planning to do a bunch of changes / addition to the r3PG package to adjust it for their purposes. This is a brainstorming list: 

![image](https://user-images.githubusercontent.com/5457753/138903041-1736edb3-aa0b-4261-9987-875f57fab43b.png)

I had suggested previously to Ramiro that it would be nice to profit from those chances for the development of r3PG, and he was asking now how this could be done in practice, i.e. how could we receive their changes e.g. via a fork, PR etc.

I will give my recommendation below, feel free to add your opinion!

**Comment by twest820** [comment]
> r3PG is under GPL3, so you can of course modify the code in whatever way you wish, as long as downstream use is compatible with GPL3 licence.

A minor comment: Licensing of git repos is often communicated by dropping a [LICENSE.md ](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#determining-the-location-of-your-license)(or equivalent) alongside README.md. Potential contributors and forkers are more likely to see a top level license file than to find this sentence or to think to look in [pkg/DESCRIPTION](https://github.com/trotsiuk/r3PG/blob/master/pkg/DESCRIPTION). Not that it's hard to search the repo for "license" but it's maybe something to consider.

**Comment by trotsiuk** [comment]
Thanks for the suggestion @twest820. Have now added the file.
