### ISSUE TITLE
Question: should we create separate, documented checkInput functions?

### ISSUE THREAD

**Issue by florianhartig** [trotsiuk/r3PG#7]
At the moment, there is the internal chk_input function.

I wonder if we should create separate, visible checkInput functions, e.g. checkSiteInput. Apart from the fact that a user could check a separate input in this way, this would provide an opportunity to document the input format for each input more clearly, without blowing up the help of the main function, i.e. the long list about the parameter inputs could be removed in favor of a link to the separate check functions.

On the other hand, a user then has to jump between help files, so not sure if it is a good idea.

**Comment by trotsiuk** [comment]
Yeh, I was also thinking about it. From one side I think it would be useful to have it as separate function, and in `run_3PR()` have it optional, e.g. `check_input = TRUE`.

For the input check, however user need to provide some / all input file. For example for the `speciesInputs` and `parameterInputs` we need to check if the number and names of the species/cohorts are identical. Therefore, the `check_input` function shall take all the tables as input. 

I think it is reasonable to have the `check_input` function as a separate function which can be extended. But first wanted to hear also opinion from others, like you.
