### ISSUE TITLE
r3PG_input.xls: Taiwanese sweet gum isn't thinned to 1500 TPH at age 10 in mixtures_other

### ISSUE THREAD

**Issue by twest820** [trotsiuk/r3PG#70]
I have some code which is quite similar to that in `r3PG_VBA_compare.R`. It sets up the management for mixtures other as given in the .xslx.
```
> siteThinning
# A tibble: 6 x 6
  species                   age stems_n  stem  root foliage
  <chr>                   <dbl>   <dbl> <dbl> <dbl>   <dbl>
1 Cunninghamia lanceolata    10    1000     1     1       1
2 Liquidambar formosana      10    1500     1     1       1
3 Cunninghamia lanceolata    15     800     1     1       1
4 Liquidambar formosana      15    1000     1     1       1
5 Cunninghamia lanceolata    20     300     1     1       1
6 Liquidambar formosana      24     200     1     1       1
```

Since Chinese fir (_Cunninghamia lanceolata_) begins with 357 TPH and Taiwanese sweet gum (_Liquidambar formosana_) with 2143 and simulation begins in January 2010 (10 year old fir and age 0 gum), two of these six thins should affect the stand trajectory, both in January 2020:
```
2 Liquidambar formosana      10    1500     1     1       1
5 Cunninghamia lanceolata    20     300     1     1       1
```
However, only the fir thinning occurs. Gum remains at 2143 TPH. This suggests an error, likely around the `t_t` and `t_n` logic, is preventing multiple thinnings from happening in a given month.
![image](https://user-images.githubusercontent.com/9359341/155854232-daa9d2a7-107f-41a3-8328-63af2807789f.png)
```
  out3PG = run_3PG(site = site, 
                   species = speciesOnSite, 
                   climate = climate, 
                   thinning = siteThinning,
                   parameters = speciesParameters, 
                   size_dist = speciesSizeDist,
                   settings = siteSettings,
                   check_input = TRUE, df_out = TRUE)
  out3PG %<>% select(-group) %>% 
    pivot_wider(names_from = variable, values_from = value) %>%
    select(-starts_with("var_"))

ggplot(mixturesOther) +
  geom_path(aes(x = date, y = stems_n, color = species, group = species))
```

**Comment by trotsiuk** [comment]
Hi @twest820, can you please provide a reproducible example as discussed previously #52 

This will much facilitate to resolve the issue.

**Comment by twest820** [comment]
Hi @trotsiuk, please find the repex in [r_vba_compare](https://github.com/trotsiuk/r3PG/tree/3e9453c36665f1612f503bde4cf7db64d6a1c041/pkg/tests/r_vba_compare).

**Comment by trotsiuk** [comment]
Todd, you are right. There was a flaw in not re-ordering the species thinning during preparation in the R `prepare_thinning`. Thus it was wrongly putting the age order (15, 10, 20). Now shall be corrected.

Please report back if still doesn't works.
