### ISSUE TITLE
Self-thinning/mortality

### ISSUE THREAD

**Issue by Rasilgon** [trotsiuk/r3PG#74]
The origin of this is issues is #65.

The self-thinning / density-dependent mortality regulates how many trees remain in the stand based on the maximum stem mass of   as:

![image](https://user-images.githubusercontent.com/10464055/158159947-6cf5a462-57e7-4624-a766-f165aae92da8.png)

where  wSx1000 defines the maximum stem mass of a tree, when n=1000 trees; and nm, aka thinPower, is the exponent of the self-thinning rule.  "When the mean individual tree stem mass ws (WS/N) is greater than wSx the N will be reduced and hence wSx will increase. his is done following an iterative procedure until ws < wSx." ([Forrester and Tang  2016](http://dx.doi.org/10.1016/j.ecolmodel.2015.07.010))

 
This mortality does not always work optimally. For low tree densities,  the value of wSx (biom_tree_max) is very high and translates into very high, even unrealistic,  stand biomass (biom_stem).  For (very) high stem numbers, the wSx is so low that many trees die in the first years of a simulation. 

These problems could be addressed by tuning/calibrating the parameters wSx1000 and thinPower, although it is not fully clear, to my knowledge, whether this mortality could always keep stand biomass within realistic ranges. Besides, there are trade-offs when doing so, and a better fit for low tree densities, might be not solve the problem with high tree densities, and vice versa.

**Comment by trotsiuk** [comment]
Hi @Rasilgon and @DavidForrester was not sure whether we aim to develop something in this direction or it is more a `comment`?
