### ISSUE TITLE
get_parameters doesn't work

### ISSUE THREAD

**Issue by SebastianBr2** [trotsiuk/r3PG#85]
Hi, I'm trying to use r3PG for the first time, but it seems the function "get_parameters" doesn't work. I created it as a function copying the corresponding code but it can't find the file "i_parameters_lit". Am I doing right? Thank you

**Comment by trotsiuk** [comment]
Hi @SebastianBr2 

Happy to hear about your interes. The function suppose to be working properly, here is the working example as described in the package.

```
library(r3PG)

get_parameters(mode = "overview", sp_names = NULL)

    parset_id                            species    age  type year                                                     region
1           1                  Tamaulipan shrubs   even  mono 2016                           Lower Rio Grande Valley, TX, USA
2           2                Eucalyptus globulus   even  mono 2016                                       Australia and Brazil
3           3                 Eucalyptus grandis   even  mono 2016                                       Australia and Brazil
```

> I created it as a function copying the corresponding code but it can't find the file "i_parameters_lit". Am I doing right? 

Why do you want to `create a function` from it? It is already a function within the package. If you create the function, then indeed it is require additional objects, like `i_parameters_lit` which is internal to the `r3PG` package.

**Comment by SebastianBr2** [comment]
Thank you for your reply! I tried to do as you suggest but R seems to be unable to find the function (but still works properly with other r3PG functions). The error is this one: 
`Error in get_parameters(mode = "overview", sp_names = NULL) : 
  could not find function "get_parameters"` 
I've imported all parameters i need from an excel I found here in github, but I don't understand if it is a problem of mine or in the package

Thank you again for your support and in general for all the work done with r3PG!

**Comment by trotsiuk** [comment]
Can you please:

- tell which `r3PG` version you are using
- run this function and provide the output:
 ```
library(r3PG)
ls("package:r3PG")
```

**Comment by SebastianBr2** [comment]
Hi,
the version is 0.1.3. The output of the function you mentioned is:
`[1] "d_climate"          "d_parameters"       "d_site"             "d_sizeDist"        
 [5] "d_species"          "d_thinning"         "i_output"           "i_parameters"      
 [9] "i_sizeDist"         "prepare_climate"    "prepare_input"      "prepare_parameters"
[13] "prepare_sizeDist"   "prepare_thinning"   "run_3PG"    `

**Comment by trotsiuk** [comment]
The function `get_parameters` was introduces in the version 0.1.4 https://github.com/trotsiuk/r3PG/releases/tag/v0.1.4

Please instal the new version and the function will be available.
