### ISSUE TITLE
Strange biomass results in mixed forest

### ISSUE THREAD

**Issue by SebastianBr2** [trotsiuk/r3PG#86]
Hi, 
I'm pretty new to r3PG. I'm trying to use it on a 1ha area with mixed composition and a simulation from 2020-01 to 2050-01. The biom_stem results are quite strange. I've tried different combinations of settings and it seems that when transp_m is set as 1, the biomass starts with the starting value I provided and it falls immediately after the first month remaining stable for the following 30 years. When transp_m is 2, the value is calculated only for 2 moments (20-01-31 and 20-02-29). I really can't explain the reason why this is happening. Do you have any ideas? Thank you so much! 

-- Here is the code I used, the 4 inputs are attached. 
`
species_cl1<-read.csv("species_cl1.csv")
site<-read.csv("site.csv")
parameters<-read.csv("parameters.csv") #obtained with get_parameters
climate0<-read.csv("climate0.csv")

 settings<-as.data.frame(t(c(2,2,2,1,0,0)))
    colnames(settings)<-c("light_model","transp_model","phys_model","height_model","correct_bias","calculate_d13c")
    
 prepare_input(site, species_cl1, climate0, thinning = NULL, parameters = parameters,
                  size_dist = NULL, settings = settings)
    output_cl1_0<-run_3PG(site, species_cl1, climate0, thinning = NULL, parameters = parameters,
                              size_dist = NULL, settings = settings, check_input = TRUE, df_out = TRUE)    

`
[site.csv](https://github.com/trotsiuk/r3PG/files/10083525/site.csv)
[species_cl1.csv](https://github.com/trotsiuk/r3PG/files/10083526/species_cl1.csv)
[climate0.csv](https://github.com/trotsiuk/r3PG/files/10083527/climate0.csv)
[parameters.csv](https://github.com/trotsiuk/r3PG/files/10083528/parameters.csv)

**Comment by SebastianBr2** [comment]
Hi @trotsiuk, 
thank you for your help! These days I've tried to simplify my runs, considering only the two main species in term of biomass. The results seem to be ok for Fagus and Pinus sylv., but when I use the parameters from q. robur and q. petraea (obtained from get_parameters) the run stops. I've tried to use Fagus parameters substituting the correspondent Quercus one by one and it seems that the problems are wSx1000 and thinPower. By now, I've used wSx1000 and thinPower from Fagus, and everything works. 
The strange aspect now is that after the first year, biom_stem decreases suddenly. The initialization condition I provided seems to not match the modeled processes. The results show a correspondent peak in thin_mortality. Here is a plot: do you have any hint about it? Thank you so much! 


![mortalità anomala cluster 3](https://user-images.githubusercontent.com/115218953/206141847-841fdbee-b197-41bc-a19c-89bad4438fa4.png)

**Comment by trotsiuk** [comment]
This is a result of the initialisation and the parameters you set. For a given density, DBH/biomass and parameters set - the density is too high. Thus there is a morality due to the self-thinning as set in the parameter.
