### ISSUE TITLE
GPP output analysis

### ISSUE THREAD

**Issue by Dieguni** [trotsiuk/r3PG#88]
Hi everyone,
I had some problems running a model which involves beech forests and their growth within the next 80 years. in particoular, as for the outputs GPP seems to decrease a lot reaching zero instead of variable such as 'voume' and biomass remain constant.
I compared my dataframes with an example I found and my the values of my input looks reliabile, so I can't really know where or why it is wrong.
These are the input and the parameters I used:
get_parameters(mode = 'parameters', sp_names = c('Fagus sylvatica 9'))
settings<-list(light_model = 1, transp_model = 1, phys_model = 1,
               height_model = 1, correct_bias = 0, calculate_d13c = 0) 
![image](https://user-images.githubusercontent.com/132576830/236207156-a91bbc06-549e-4a7a-83a7-ef8bd83c6812.png)
![image](https://user-images.githubusercontent.com/132576830/236207820-09f06abe-80d6-41ed-8c41-880ff3b9c8c3.png)

**Comment by trotsiuk** [comment]
Hi @Dieguni 

For the easier check from our side, please consider including the **reproducible example**, which would include code and input data (in. e.g. csv).

From the quick look, your issue sounds to be related to previously described in #65

**Comment by Dieguni** [comment]
Thanks for the answer! Of course I should have pasted inputs and codes...here they are. Now I should have linked every necessary tools (I'm a newby). 


#import
climate26<-read.csv2("CF 2.6/climate_input_2.6.csv")
siteCF<-read.csv2("CF 2.6/CF_site.csv")                     
speciesCF<-read.csv2("CF 2.6/CF_species.csv")

#site
siteCF[,c(1,2,6)]<-lapply(siteCF[,c(1,2,6)], as.numeric)

#species 
names(speciesCF)[4]<-"stems_n"
speciesCF[,3:7]<- lapply(speciesCF[,3:7], as.numeric)

#parameters
overview <- get_parameters(mode = "overview", sp_names = NULL)
# poi aprire il dataframe overview e trovare la colonna con la specie che ti serve (se c'è un numero copia anche quello nel passaggio successivo!!)
parametersCF<-get_parameters(mode = 'parameters', sp_names = c('Fagus sylvatica 9'))

#settings
settingsCF<-list(light_model = 1, transp_model = 1, phys_model = 1,
               height_model = 1, correct_bias = 0, calculate_d13c = 0) 


#climate
climate26<- lapply(climate26, as.numeric)
climate26<-prepare_climate(climate26, from="2020-01" , to="2100-01")


#run
prepare_input(siteCF, speciesCF, climate26, thinning = NULL, parameters = parametersCF,
              size_dist = NULL, settings = settingsCF)


outputCF26<-run_3PG(siteCF, speciesCF, climate26, thinning = NULL, parameters = parametersCF,
                size_dist = NULL, settings = settingsCF, check_input = TRUE, df_out = TRUE)    

#RAPPRESENTAZIONE 
levels(as.factor(outputCF26$variable))   

sel_var <- c('mort_stress', 'asw', 'lai', 'stems_n') #seleziona le variabili che vuoi vedere

outputCF26 %>%
  filter( variable %in% sel_var ) %>%
  ggplot( aes(date, value, color = species) ) +
  geom_line() +
  facet_wrap(~variable, scales = 'free') +
  theme_classic()
[CF_site.csv](https://github.com/trotsiuk/r3PG/files/11405396/CF_site.csv)
[CF_species.csv](https://github.com/trotsiuk/r3PG/files/11405397/CF_species.csv)
[climate_input_2.6.csv](https://github.com/trotsiuk/r3PG/files/11405398/climate_input_2.6.csv)
