### ISSUE TITLE
Allometric parameterisation for Chestnut

### ISSUE THREAD

**Issue by SebastianBr2** [trotsiuk/r3PG#99]
Hi! 
I've recently tried to parametrize chestnut, finding parameters both in literature and in other models that already have this species parametrized. For the few missing parameters, I've used parameters from other species like beech. 
Since it is a mix, I've set the parameters light_model, transp_model and phys_model = 2, but in this way chestnut doesn't grow. I've tried to set the light model = 1 and it grows. 

I'm wondering: what could be the explanation? is there some error in my parametrization? which parameters are more sensitive to this fact? 
Thank you so much! 

[species_csmix.csv](https://github.com/trotsiuk/r3PG/files/13491060/species_csmix.csv)
[climate_hist.csv](https://github.com/trotsiuk/r3PG/files/13491062/climate_hist.csv)
[param_mix.csv](https://github.com/trotsiuk/r3PG/files/13491063/param_mix.csv)
[site.csv](https://github.com/trotsiuk/r3PG/files/13491064/site.csv)

```
library(dplyr)
library(ggplot2)
library(r3PG)

#wd 
setwd("C:/Users/Sebastian/OneDrive - Università degli Studi di Milano/PNATE carbon/chestnut_check")
#import ####
site_generic <- read.csv("site.csv")
param_lat <- read.csv("param_mix.csv")
species_csmix <- read.csv("species_csmix.csv")
species_onlycs <- read.csv("species_onlycs.csv")
climate_hist <- read.csv("climate_hist.csv")

#settings 
settings_cs<-list(light_model = 2, transp_model = 2, phys_model = 2,
                  height_model = 2, correct_bias = 0, calculate_d13c = 0)
settings_cs1<-list(light_model = 1, transp_model = 2, phys_model = 2,
                  height_model = 2, correct_bias = 0, calculate_d13c = 0)
#variables 
sel_var <- c('biom_stem', 'biom_root', 'biom_foliage',
                        'biom_incr_stem', 'stems_n', 'gpp')

#mix beech and chestnut (light model 2) 
out_cs_mix_hist <-  run_3PG(
  site        = site_generic, 
  species     = species_csmix, 
  climate     = climate_hist, 
  thinning    = NULL,
  parameters  = param_lat, 
  size_dist   = NULL,
  settings    = settings_cs,
  check_input = TRUE, df_out = TRUE)

out_cs_mix_hist %>%
  filter( variable %in% sel_var ) %>%
  ggplot( aes(date, value, color = species) ) +
  geom_line(size = 0.8, alpha = 0.5) +
  facet_wrap(~variable, scales = 'free') +
  theme_classic() + 
  ggtitle("beech and chestnut - Historic climate")


#mix beech and chestnut (light model 1) 
out_cs_mix_hist <-  run_3PG(
  site        = site_generic, 
  species     = species_csmix, 
  climate     = climate_hist, 
  thinning    = NULL,
  parameters  = param_lat, 
  size_dist   = NULL,
  settings    = settings_cs1,
  check_input = TRUE, df_out = TRUE)

out_cs_mix_hist %>%
  filter( variable %in% sel_var ) %>%
  ggplot( aes(date, value, color = species) ) +
  geom_line(size = 0.8, alpha = 0.5) +
  facet_wrap(~variable, scales = 'free') +
  theme_classic() + 
  ggtitle("beech and chestnut - Historic climate")

```

**Comment by SebastianBr2** [comment]
It seems that the problem is allometric parameters, since when I substitute them with the beech ones everything works properly. I think the problem could be that I've calculated chestnut allometric parameters with very data and maybe the regressions weren't good enough.

**Comment by trotsiuk** [comment]
Hi @SebastianBr2 , It is very likely that the parameters are the main cause of the issue. To identify and eliminate the issue it is usually advised to go step by step:

- run the simulation only for one species 
- adjust settings for that species, and observe whether the behaviour change
- add the mixture and check whether there is change in behaviour.

As you have already mentioned, the allometric parameters might be the reason.
